### ISSUE TITLE
[Feature suggestion] Indicate used satellites on bar graph page

### ISSUE THREAD

**Issue by Olf0** [direc85/sailfish-gpsinfo#16] opened 2020-01-05 16:48 UTC
Please also indicate on the bar graph page, which satellites are currently in use, as it is already the case on the polar view page.
Preferably with the same way of indicating a satellite's use: a white outline around the coloured area (which depicts the satellite's signal strength).

The usefulness of this became apparent when trying to look further into the [observation made in this side note](https://github.com/direc85/harbour-gpsinfo/issues/11#issuecomment-570925982).

**Comment by direc85** [comment] 2020-01-05 19:16
Thanks for the report. I was actually planning to open this myself, this was already mentioned in issue #4 

The issue is QChart.js, which doesn't offer a method to highlight a bar easily, so the options are patching QChart.js or reimplementing it. After seeing the performance boost my [radar view rewrite](https://github.com/direc85/harbour-gpsinfo/commit/bfb74fd22cba2b8841727b702c3335027612492a) had, I'm going to implement similar graph drawing method in QML.

**Comment by Olf0** [comment] 2020-01-05 20:36
Thanks for the prompt and positive reply.

##### A second thought
Actually outlining the bars was a bad idea:
* The outlines at the sides of the bar need additional horizontal space, thus reducing the width of the coloured part of the bars.
* Outlines at the sides of the bars create the corner case of two adjacent bars being outlined: A double width outline might look ugly and occupies even more horizontal space.
* An outline at the bottom of the bars is simply superfluous and may look weird.

So I think the top of the bars is the right spot to position an "in use" indicator.
Maybe a simple white "top line" is sufficient to achieve this easily.

**Comment by sbridger** [comment] 2021-05-31 20:51
I have implemented this by changing bar colour: All active bars are the rssi color (like now) . inactive bars are all the same scale draw color.
I tried to use border color, width and label color, but they do nothing. Chart does appear to put fine lines in the grid color around the bars (visible when you make the bar color "transparent")

I have been wasting time after finding that when I delete your gpsinfo install, my version doesn't run because Chart is unknown. I have just found that pulling gpsinfo from GH _does_ make the chart folder, but _does not_ get any of the files inside it. However none of it is part of the project file, so I have no idea where Chart came from.

Do you need to add QChart to the project file?

**Comment by direc85** [comment] 2022-03-20 21:20
This is now "implemented-enough" in an already released version, so this can be closed. I'm still going to rewrite the barchart page to do without the external chart element - much like what I did to the radar page - but it's outside this issue.

Closing as fixed :)

**Closed as completed by direc85** 2022-03-20 21:20 UTC
Labels: enhancement
